version: '3.0'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
     - "8080:8080"
    volumes:
     - ./service-discovery:/app
     - ~/.m2:/root/.m2
    networks:
     - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
     - "8084:8080"
    volumes:
     - ./auth-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
     - "8083:8080"
    volumes:
     - ./gateway-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  cliente-service:
    build:
      context: ./cliente-service
    container_name: cliente-service
    ports:
     - "8085:8080"
    volumes:
     - ./cliente-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  veiculo-service:
    build:
      context: ./veiculo-service
    container_name: veiculo-service
    ports:
     - "8086:8080"
    volumes:
     - ./veiculo-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  reserva-service:
    build:
      context: ./reserva-service
    container_name: reserva-service
    ports:
     - "8087:8080"
    volumes:
     - ./reserva-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  contrato-service:
    build:
      context: ./contrato-service
    container_name: contrato-service
    ports:
     - "8088:8080"
    volumes:
     - ./contrato-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  faturamento-service:
    build:
      context: ./faturamento-service
    container_name: faturamento-service
    ports:
     - "8089:8080"
    volumes:
     - ./faturamento-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  manutencao-service:
    build:
      context: ./manutencao-service
    container_name: manutencao-service
    ports:
     - "8090:8080"
    volumes:
     - ./manutencao-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  relatorio-service:
    build:
      context: ./relatorio-service
    container_name: relatorio-service
    ports:
     - "8091:8080"
    volumes:
     - ./relatorio-service:/app
     - ~/.m2:/root/.m2
    depends_on:
     - service-discovery
    networks:
     - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - auth-service
     - gateway-service
     - cliente-service
     - veiculo-service
     - reserva-service
     - contrato-service
     - faturamento-service
     - manutencao-service
     - relatorio-service
    networks:
     - app-network

networks:
  app-network:
    driver: bridge
